"""add_all_models_from_thom

Revision ID: 6516cfd536c1
Revises: 9c8b676f6ec5
Create Date: 2026-09-07 16:04:47.617304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6516cfd536c1'
down_revision: Union[str, Sequence[str], None] = '9c8b676f6ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
