"""create book embeddings table

Revision ID: 161868ae43c2
Revises: 3f21d9a7c4b2
Create Date: 2026-09-17 21:09:31.976537

"""

from collections.abc import Sequence
from typing import Union

import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "161868ae43c2"
down_revision: Union[str, None] = "3f21d9a7c4b2"  # noqa: UP007
branch_labels: Union[str, Sequence[str], None] = None  # noqa: UP007
depends_on: Union[str, Sequence[str], None] = None  # noqa: UP007


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "book_embeddings",
        sa.Column("book_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
            name=op.f("fk_book_embeddings_book_id_books"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_book_embeddings")),
    )
    op.create_index(op.f("ix_book_embeddings_book_id"), "book_embeddings", ["book_id"], unique=True)
    op.create_index(
        op.f("ix_book_embeddings_content_hash"), "book_embeddings", ["content_hash"], unique=False
    )
    op.drop_constraint(op.f("ck_books_book_quantities_valid"), "books", type_="check")
    op.drop_constraint(
        op.f("ck_borrow_items_borrow_item_quantity_positive"), "borrow_items", type_="check"
    )
    op.drop_constraint(
        op.f("ck_reservation_items_reservation_item_quantity_positive"),
        "reservation_items",
        type_="check",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        op.f("ck_reservation_items_reservation_item_quantity_positive"),
        "reservation_items",
        "quantity > 0",
    )
    op.create_check_constraint(
        op.f("ck_borrow_items_borrow_item_quantity_positive"), "borrow_items", "quantity > 0"
    )
    op.create_check_constraint(
        op.f("ck_books_book_quantities_valid"),
        "books",
        "quantity >= 0 AND available_quantity >= 0 AND available_quantity <= quantity",
    )
    op.drop_index(op.f("ix_book_embeddings_content_hash"), table_name="book_embeddings")
    op.drop_index(op.f("ix_book_embeddings_book_id"), table_name="book_embeddings")
    op.drop_table("book_embeddings")
    # ### end Alembic commands ###
