"""add author_id to books

Revision ID: 5ab6e681bf26
Revises: 3f21d9a7c4b2
Create Date: 2026-09-17 17:39:23.312437

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ab6e681bf26"
down_revision: str | None = "3f21d9a7c4b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("author_id", sa.UUID(), nullable=False))
    op.create_index(op.f("ix_books_author_id"), "books", ["author_id"], unique=False)
    op.create_foreign_key(op.f("fk_books_author_id_authors"), "books", "authors", ["author_id"], ["id"])
    op.drop_constraint(op.f("ck_books_book_quantities_valid"), "books", type_="check")
    op.drop_constraint(op.f("ck_borrow_items_borrow_item_quantity_positive"), "borrow_items", type_="check")
    op.drop_constraint(
        op.f("ck_reservation_items_reservation_item_quantity_positive"), "reservation_items", type_="check"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        op.f("ck_reservation_items_reservation_item_quantity_positive"), "reservation_items", "quantity > 0"
    )
    op.create_check_constraint(op.f("ck_borrow_items_borrow_item_quantity_positive"), "borrow_items", "quantity > 0")
    op.create_check_constraint(
        op.f("ck_books_book_quantities_valid"),
        "books",
        "quantity >= 0 AND available_quantity >= 0 AND available_quantity <= quantity",
    )
    op.drop_constraint(op.f("fk_books_author_id_authors"), "books", type_="foreignkey")
    op.drop_index(op.f("ix_books_author_id"), table_name="books")
    op.drop_column("books", "author_id")
    # ### end Alembic commands ###
