"""create library tables

Revision ID: 8ab5704e174b
Revises: f854c08d0be1
Create Date: 2026-08-17 16:16:56.454961

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ab5704e174b"
down_revision: Union[str, None] = "f854c08d0be1"  # noqa: UP007
branch_labels: Union[str, Sequence[str], None] = None  # noqa: UP007
depends_on: Union[str, Sequence[str], None] = None  # noqa: UP007


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authors")),
    )
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_categories_name")),
    )
    op.create_table(
        "publishers",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publishers")),
    )
    op.create_table(
        "ai_search_logs",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("result_book_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_ai_search_logs_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_search_logs")),
    )
    op.create_index(op.f("ix_ai_search_logs_user_id"), "ai_search_logs", ["user_id"], unique=False)
    op.create_table(
        "books",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("isbn", sa.String(length=20), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("publisher_id", sa.UUID(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("available_quantity", sa.Integer(), nullable=False),
        sa.Column("published_year", sa.SmallInteger(), nullable=True),
        sa.Column("cover_image_url", sa.String(length=500), nullable=True),
        sa.Column("cover_image_storage_key", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name=op.f("fk_books_category_id_categories")
        ),
        sa.ForeignKeyConstraint(
            ["publisher_id"],
            ["publishers.id"],
            name=op.f("fk_books_publisher_id_publishers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_books")),
    )
    op.create_index(op.f("ix_books_category_id"), "books", ["category_id"], unique=False)
    op.create_index(op.f("ix_books_isbn"), "books", ["isbn"], unique=True)
    op.create_index(op.f("ix_books_publisher_id"), "books", ["publisher_id"], unique=False)
    op.create_index(
        "ix_books_title_trgm",
        "books",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.create_table(
        "reservations",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "cancelled", "expired", name="reservation_status"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_reservations_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservations")),
    )
    op.create_index(
        "ix_reservations_user_id_status", "reservations", ["user_id", "status"], unique=False
    )
    op.create_table(
        "book_authors",
        sa.Column("book_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
            name=op.f("fk_book_authors_author_id_authors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
            name=op.f("fk_book_authors_book_id_books"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("book_id", "author_id", name=op.f("pk_book_authors")),
    )
    op.create_index("ix_book_authors_author_id", "book_authors", ["author_id"], unique=False)
    op.create_table(
        "borrow_records",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("reservation_id", sa.UUID(), nullable=True),
        sa.Column("borrow_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("return_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("borrowing", "returned", "overdue", name="borrow_status"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
            name=op.f("fk_borrow_records_reservation_id_reservations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_borrow_records_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_borrow_records")),
    )
    op.create_index(
        op.f("ix_borrow_records_due_date"), "borrow_records", ["due_date"], unique=False
    )
    op.create_index(
        op.f("ix_borrow_records_reservation_id"), "borrow_records", ["reservation_id"], unique=False
    )
    op.create_index(
        "ix_borrow_records_user_id_status", "borrow_records", ["user_id", "status"], unique=False
    )
    op.create_table(
        "reservation_items",
        sa.Column("reservation_id", sa.UUID(), nullable=False),
        sa.Column("book_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_reservation_items_book_id_books")
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
            name=op.f("fk_reservation_items_reservation_id_reservations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservation_items")),
    )
    op.create_index(
        op.f("ix_reservation_items_book_id"), "reservation_items", ["book_id"], unique=False
    )
    op.create_index(
        op.f("ix_reservation_items_reservation_id"),
        "reservation_items",
        ["reservation_id"],
        unique=False,
    )
    op.create_table(
        "borrow_items",
        sa.Column("borrow_id", sa.UUID(), nullable=False),
        sa.Column("book_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("returned", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_borrow_items_book_id_books")
        ),
        sa.ForeignKeyConstraint(
            ["borrow_id"],
            ["borrow_records.id"],
            name=op.f("fk_borrow_items_borrow_id_borrow_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_borrow_items")),
    )
    op.create_index(op.f("ix_borrow_items_book_id"), "borrow_items", ["book_id"], unique=False)
    op.create_index(op.f("ix_borrow_items_borrow_id"), "borrow_items", ["borrow_id"], unique=False)
    op.create_table(
        "fines",
        sa.Column("borrow_record_id", sa.UUID(), nullable=False),
        sa.Column("overdue_days", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "payment_status", sa.Enum("unpaid", "paid", name="payment_status"), nullable=False
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["borrow_record_id"],
            ["borrow_records.id"],
            name=op.f("fk_fines_borrow_record_id_borrow_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fines")),
        sa.UniqueConstraint("borrow_record_id", name=op.f("uq_fines_borrow_record_id")),
    )
    op.create_index(op.f("ix_fines_payment_status"), "fines", ["payment_status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fines_payment_status"), table_name="fines")
    op.drop_table("fines")
    op.drop_index(op.f("ix_borrow_items_borrow_id"), table_name="borrow_items")
    op.drop_index(op.f("ix_borrow_items_book_id"), table_name="borrow_items")
    op.drop_table("borrow_items")
    op.drop_index(op.f("ix_reservation_items_reservation_id"), table_name="reservation_items")
    op.drop_index(op.f("ix_reservation_items_book_id"), table_name="reservation_items")
    op.drop_table("reservation_items")
    op.drop_index("ix_borrow_records_user_id_status", table_name="borrow_records")
    op.drop_index(op.f("ix_borrow_records_reservation_id"), table_name="borrow_records")
    op.drop_index(op.f("ix_borrow_records_due_date"), table_name="borrow_records")
    op.drop_table("borrow_records")
    op.drop_index("ix_book_authors_author_id", table_name="book_authors")
    op.drop_table("book_authors")
    op.drop_index("ix_reservations_user_id_status", table_name="reservations")
    op.drop_table("reservations")
    op.drop_index(
        "ix_books_title_trgm",
        table_name="books",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_books_publisher_id"), table_name="books")
    op.drop_index(op.f("ix_books_isbn"), table_name="books")
    op.drop_index(op.f("ix_books_category_id"), table_name="books")
    op.drop_table("books")
    op.drop_index(op.f("ix_ai_search_logs_user_id"), table_name="ai_search_logs")
    op.drop_table("ai_search_logs")
    op.drop_table("publishers")
    op.drop_table("categories")
    op.drop_table("authors")
    # ### end Alembic commands ###
