"""remove unused cloudinary storage fields

Revision ID: cb66150fe45c
Revises: d90ed9debb8e
Create Date: 2026-09-18 21:45:58.243993

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb66150fe45c"
down_revision: str | None = "d90ed9debb8e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "cover_image_storage_key")
    op.drop_column("users", "avatar_storage_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("avatar_storage_key", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "books",
        sa.Column(
            "cover_image_storage_key", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
