"""remove unused ai search logs

Revision ID: d90ed9debb8e
Revises: 161868ae43c2
Create Date: 2026-09-18 21:05:18.946189

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d90ed9debb8e"
down_revision: Union[str, None] = "161868ae43c2"  # noqa: UP007
branch_labels: Union[str, Sequence[str], None] = None  # noqa: UP007
depends_on: Union[str, Sequence[str], None] = None  # noqa: UP007


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ai_search_logs_user_id"), table_name="ai_search_logs")
    op.drop_table("ai_search_logs")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_search_logs",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("query_text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "result_book_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_ai_search_logs_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_search_logs")),
    )
    op.create_index(op.f("ix_ai_search_logs_user_id"), "ai_search_logs", ["user_id"], unique=False)
    # ### end Alembic commands ###
