"""update table users

Revision ID: f854c08d0be1
Revises: fca35a750b5e
Create Date: 2026-08-17 16:04:42.363202

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f854c08d0be1"
down_revision: Union[str, None] = "fca35a750b5e"  # noqa: UP007
branch_labels: Union[str, Sequence[str], None] = None  # noqa: UP007
depends_on: Union[str, Sequence[str], None] = None  # noqa: UP007


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("avatar_url", sa.String(length=500), nullable=True))
    op.add_column("users", sa.Column("avatar_storage_key", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar_storage_key")
    op.drop_column("users", "avatar_url")
    # ### end Alembic commands ###
